export const url = {
  api: {
    auth: 'auth',
    establishments: 'establishments',
    playingFields: 'playing-fields',
    reservations: 'reservations',
    employees: 'employees',
    roles: 'roles',
    items: 'items',
    itemCategories: 'item-categories',
    users: 'users',
  },
  web: {
    login: 'login',
    reservations: 'reservations',
    createReservation: 'create-reservation',
    createClass: 'create-class',
    users: 'users',
    employees: 'employees',
    items: 'items',
    categories: 'categories',
    playingFields: 'playing-fields',
    establishments: 'establishments',
  },
}
